---
date: "2020-06-22T00:00:00Z"
image:
  caption: 
  focal_point: Smart
summary: Creating a dashboard for visualizing zooplankton in the Indian Ocean
tags:
- dashboard
- DNA metabarcoding
- R
- flexdashboard
- DNA 
- Visualizations
- Data Visualization
title: Who's who in the zoo
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---
Page 1
===============================================================

```{r setup, include=FALSE}
library(tidyverse)
library(DT)
library(flexdashboard)
library(jsonlite)
library(rjson)
library(r2d3)
library(shiny)

zoo <- read_json("Aliwal02.json")
startData <- read.csv("ALIWAL.csv")
GBChoices <- as.list(names(startData))
names(GBChoices) <- paste(names(startData),map(startData,~length(unique(.x))))

updateData <- reactive(
  startData %>% group_by(!!! rlang::syms(input$GB)) %>% summarise_if(is.numeric,sum,na.rm=T))
```
Row {data-width=150}
-------------------------------------------------------------------

### No. of classes sequenced
```{r}
family= length(unique(startData[["Class"]]))
valueBox(value = family, caption = "Classes sequenced",color = "red")
```

### No. of orders sequenced
```{r}
family= length(unique(startData[["Order"]]))
valueBox(value = family, caption = "Orders sequenced",color = "green")
```


### No. of genera sequenced
```{r}
genera=length(unique(startData[["Genus"]]))
valueBox(value = genera, caption = "Genera sequenced", color = "orange")
```

### No. of species sequenced
```{r}
species=length(unique(startData[["OTU"]]))
valueBox(value = species, caption = "Species sequenced", color = "blue")
```



Column {.sidebar}
------------------------------------------------------------------
```{r}
selectInput(inputId = "GB",label = "Group By",choices = GBChoices)
selectInput(inputId = "Metric",label = "Metric",choices = names(select_if(startData,is.numeric)))
```

Row
------------------------------------------------------------------

### Plot
```{r}
renderPlot({
 updateData() %>% 
  ggplot(aes(x=!! rlang::sym(input$GB),y=!! rlang::sym(input$Metric),fill=!! rlang::sym(input$GB))) +
  geom_col()
})
```


### Table 
```{r}
renderDT(
  updateData(), rownames = F, extensions = 'Buttons', filter="top", editable=T,
  options = list(
    dom = 'Blfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
    lengthMenu = list(c(10,50,100,-1),c(10,50,100,"All"))
  )
)
```

Row {data-width=650}
-----------------------------------------------------------------------

### Zooplankton
```{d3 data= zoo}

const format = d3.format(",d");
const minWidthHeight = Math.min(width, height);
const radius = minWidthHeight / 6;

const arc = d3.arc()
    .startAngle(d => d.x0)
    .endAngle(d => d.x1)
    .padAngle(d => Math.min((d.x1 - d.x0) / 2, 0.005))
    .padRadius(radius * 1.5)
    .innerRadius(d => d.y0 * radius)
    .outerRadius(d => Math.max(d.y0 * radius, d.y1 * radius - 1));

const partition = data => {
    const root = d3.hierarchy(data)
        .sum(d => d.size)
        .sort((a, b) => b.value - a.value);
    return d3.partition()
        .size([2 * Math.PI, root.height + 1])
        (root);
}

const root = partition(data);
const color = d3.scaleOrdinal().range(d3.quantize(d3.interpolateRainbow, data.children.length + 1));

root.each(d => d.current = d);

svg = svg
    .style("width", "100%")
    .style("height", "auto")
    .style("font", "10px sans-serif");

const g = svg.append("g")
    .attr("transform", `translate(${width / 2},${height / 2})`);

const path = g.append("g")
    .selectAll("path")
    .data(root.descendants().slice(1))
    .enter().append("path")
    .attr("fill", d => {
        while (d.depth > 1)
            d = d.parent;
        return color(d.data.name);
    })
    .attr("fill-opacity", d => arcVisible(d.current) ? (d.children ? 0.6 : 0.4) : 0)
    .attr("d", d => arc(d.current));

path.filter(d => d.children)
    .style("cursor", "pointer")
    .on("click", clicked);

path.append("title")
    .text(d => `${d.ancestors().map(d => d.data.name).reverse().join("/")}\n${format(d.value)}`);

const label = g.append("g")
    .attr("pointer-events", "none")
    .attr("text-anchor", "middle")
    .style("user-select", "none")
    .selectAll("text")
    .data(root.descendants().slice(1))
    .enter().append("text")
    .attr("dy", "0.35em")
    .attr("fill-opacity", d => +labelVisible(d.current))
    .attr("transform", d => labelTransform(d.current))
    .text(d => d.data.name);

const parentNode = g.append("circle")
    .datum(root)
    .attr("r", radius)
    .attr("fill", "none")
    .attr("pointer-events", "all")
    .on("click", clicked);

function clicked(p) {
    parentNode.datum(p.parent || root);

    root.each(d => d.target = {
        x0: Math.max(0, Math.min(1, (d.x0 - p.x0) / (p.x1 - p.x0))) * 2 * Math.PI,
        x1: Math.max(0, Math.min(1, (d.x1 - p.x0) / (p.x1 - p.x0))) * 2 * Math.PI,
        y0: Math.max(0, d.y0 - p.depth),
        y1: Math.max(0, d.y1 - p.depth)
    });

    const t = g.transition().duration(750);

    // Transition the data on all arcs, even the ones that aren't visible,
    // so that if this transition is interrupted, entering arcs will start
    // the next transition from the desired position.
    path.transition(t)
        .tween("data", d => {
            const i = d3.interpolate(d.current, d.target);
            return t => d.current = i(t);
        })
        .filter(function (d) {
            return +this.getAttribute("fill-opacity") || arcVisible(d.target);
        })
        .attr("fill-opacity", d => arcVisible(d.target) ? (d.children ? 0.6 : 0.4) : 0)
        .attrTween("d", d => () => arc(d.current));

    label.filter(function (d) {
        return +this.getAttribute("fill-opacity") || labelVisible(d.target);
    }).transition(t)
        .attr("fill-opacity", d => +labelVisible(d.target))
        .attrTween("transform", d => () => labelTransform(d.current));
}

function arcVisible(d) {
    return d.y1 <= 3 && d.y0 >= 1 && d.x1 > d.x0;
}

function labelVisible(d) {
    return d.y1 <= 3 && d.y0 >= 1 && (d.y1 - d.y0) * (d.x1 - d.x0) > 0.03;
}

function labelTransform(d) {
    const x = (d.x0 + d.x1) / 2 * 180 / Math.PI;
    const y = (d.y0 + d.y1) / 2 * radius;
    return `rotate(${x - 90}) translate(${y},0) rotate(${x < 180 ? 0 : 180})`;
}

```

Page 2
===============================================================

```{r , include=FALSE}

dbn <- read_json("DBN_01.json")
startDbn <- read.csv("DBN01_SB.csv")
dbnGBChoices <- as.list(names(startDbn))
names(dbnGBChoices) <- paste(names(startDbn),map(startDbn,~length(unique(.x))))

updateDatadbn <- reactive(
  startDbn %>% group_by(!!! rlang::syms(input$GB)) %>% summarise_if(is.numeric,sum,na.rm=T))
```
Row {data-width=150}
-------------------------------------------------------------------

### No. of classes sequenced
```{r}
familydbn= length(unique(startDbn[["Class"]]))
valueBox(value = familydbn, caption = "Classes sequenced",color = "red")
```

### No. of orders sequenced
```{r}
OrderDbn= length(unique(startDbn[["Order"]]))
valueBox(value = OrderDbn, caption = "Orders sequenced",color = "green")
```


### No. of genera sequenced
```{r}
generaDbn=length(unique(startDbn[["Genus"]]))
valueBox(value = generaDbn, caption = "Genera sequenced", color = "orange")
```

### No. of species sequenced
```{r}
speciesDbn=length(unique(startDbn[["OTU"]]))
valueBox(value = speciesDbn, caption = "Species sequenced", color = "blue")
```



Column {.sidebar}
------------------------------------------------------------------
```{r}
selectInput(inputId = "GB",label = "Group By",choices = dbnGBChoices)
selectInput(inputId = "Metric",label = "Metric",choices = names(select_if(startDbn,is.numeric)))
```

Row
------------------------------------------------------------------

### Plot
```{r}
renderPlot({
 updateData() %>% 
  ggplot(aes(x=!! rlang::sym(input$GB),y=!! rlang::sym(input$Metric),fill=!! rlang::sym(input$GB))) +
  geom_col()
})
```


### Table 
```{r}
renderDT(
  updateData(), rownames = F, extensions = 'Buttons', filter="top", editable=T,
  options = list(
    dom = 'Blfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
    lengthMenu = list(c(10,50,100,-1),c(10,50,100,"All"))
  )
)
```

Row {data-width=650}
-----------------------------------------------------------------------

### Zooplankton
```{d3 data= dbn}

const format = d3.format(",d");
const minWidthHeight = Math.min(width, height);
const radius = minWidthHeight / 6;

const arc = d3.arc()
    .startAngle(d => d.x0)
    .endAngle(d => d.x1)
    .padAngle(d => Math.min((d.x1 - d.x0) / 2, 0.005))
    .padRadius(radius * 1.5)
    .innerRadius(d => d.y0 * radius)
    .outerRadius(d => Math.max(d.y0 * radius, d.y1 * radius - 1));

const partition = data => {
    const root = d3.hierarchy(data)
        .sum(d => d.size)
        .sort((a, b) => b.value - a.value);
    return d3.partition()
        .size([2 * Math.PI, root.height + 1])
        (root);
}

const root = partition(data);
const color = d3.scaleOrdinal().range(d3.quantize(d3.interpolateRainbow, data.children.length + 1));

root.each(d => d.current = d);

svg = svg
    .style("width", "100%")
    .style("height", "auto")
    .style("font", "10px sans-serif");

const g = svg.append("g")
    .attr("transform", `translate(${width / 2},${height / 2})`);

const path = g.append("g")
    .selectAll("path")
    .data(root.descendants().slice(1))
    .enter().append("path")
    .attr("fill", d => {
        while (d.depth > 1)
            d = d.parent;
        return color(d.data.name);
    })
    .attr("fill-opacity", d => arcVisible(d.current) ? (d.children ? 0.6 : 0.4) : 0)
    .attr("d", d => arc(d.current));

path.filter(d => d.children)
    .style("cursor", "pointer")
    .on("click", clicked);

path.append("title")
    .text(d => `${d.ancestors().map(d => d.data.name).reverse().join("/")}\n${format(d.value)}`);

const label = g.append("g")
    .attr("pointer-events", "none")
    .attr("text-anchor", "middle")
    .style("user-select", "none")
    .selectAll("text")
    .data(root.descendants().slice(1))
    .enter().append("text")
    .attr("dy", "0.35em")
    .attr("fill-opacity", d => +labelVisible(d.current))
    .attr("transform", d => labelTransform(d.current))
    .text(d => d.data.name);

const parentNode = g.append("circle")
    .datum(root)
    .attr("r", radius)
    .attr("fill", "none")
    .attr("pointer-events", "all")
    .on("click", clicked);

function clicked(p) {
    parentNode.datum(p.parent || root);

    root.each(d => d.target = {
        x0: Math.max(0, Math.min(1, (d.x0 - p.x0) / (p.x1 - p.x0))) * 2 * Math.PI,
        x1: Math.max(0, Math.min(1, (d.x1 - p.x0) / (p.x1 - p.x0))) * 2 * Math.PI,
        y0: Math.max(0, d.y0 - p.depth),
        y1: Math.max(0, d.y1 - p.depth)
    });

    const t = g.transition().duration(750);

    // Transition the data on all arcs, even the ones that aren't visible,
    // so that if this transition is interrupted, entering arcs will start
    // the next transition from the desired position.
    path.transition(t)
        .tween("data", d => {
            const i = d3.interpolate(d.current, d.target);
            return t => d.current = i(t);
        })
        .filter(function (d) {
            return +this.getAttribute("fill-opacity") || arcVisible(d.target);
        })
        .attr("fill-opacity", d => arcVisible(d.target) ? (d.children ? 0.6 : 0.4) : 0)
        .attrTween("d", d => () => arc(d.current));

    label.filter(function (d) {
        return +this.getAttribute("fill-opacity") || labelVisible(d.target);
    }).transition(t)
        .attr("fill-opacity", d => +labelVisible(d.target))
        .attrTween("transform", d => () => labelTransform(d.current));
}

function arcVisible(d) {
    return d.y1 <= 3 && d.y0 >= 1 && d.x1 > d.x0;
}

function labelVisible(d) {
    return d.y1 <= 3 && d.y0 >= 1 && (d.y1 - d.y0) * (d.x1 - d.x0) > 0.03;
}

function labelTransform(d) {
    const x = (d.x0 + d.x1) / 2 * 180 / Math.PI;
    const y = (d.y0 + d.y1) / 2 * radius;
    return `rotate(${x - 90}) translate(${y},0) rotate(${x < 180 ? 0 : 180})`;
}

```